modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="silencemod"
version="1.0.0"
displayName="Silence Mod"
description='''
This mod filters chat messages and disables network for specific mods.
'''

[[dependencies.silencemod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.silencemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"